import type { Product } from '../../types/product';

export const MOCK_DATA: Product[] = [
  {
    PK: 'PRODUCT#origami',
    SK: 'METADATA',
    name: 'Origami Dripper - Air S',
    description: 'Minimalist top-down view of a lavender Origami porcelain dripper resting on a light wood surface with architectural shadows',
    price: 48.00,
    stock: 15,
    media: [{ type: 'image', key: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAPLh35CcUN6-OOOiDqVqkykGgBBFpWZ6WwpStWdw1TVWjoupIzr_Z-p20whcbl3cUoN3gBqb2K0nitD2kmVHD46nyribroP2zZys9oLNHBRg72QPBccqSXRfC5H0T0YHKTSA1YZdFeJThn5VFUWphQRPrp-t5XRrXK8cwX0NN6m1WMSEPeeSpTRqDWpoBnoyhdFN9grQT_5U5grtWG2fOPyGMD2wLFTp1C_Iue5SODIvyljdVvS_DYEt-g_Zi6qHoayB01fcwG0-I', isMain: true }],
    categories: [{ name: 'Origami', slug: 'origami' }],
    version: 1,
    created_at: Date.now(),
  },
  {
    PK: 'PRODUCT#hario',
    SK: 'METADATA',
    name: 'Hario V60 Switch',
    description: 'Close-up of a matte black metal Hario V60 dripper with dramatic side lighting highlighting its ribbed interior texture',
    price: 65.00,
    stock: 10,
    media: [{ type: 'image', key: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA84g-zX3c7jk7iQP8Rst5NgyNQBzXjJCHkbWwUptW_u79VAgZ1J8gyClBGr44C00bF8iKu6K6cHOl4tLED3p6HWgicz39dBKL4htd-kPqTtC__NSbD4csZsnZuVqLPxS4QXWegGapTLGBhmzm-qUKrF_EeEuerwcYU3mdYepJlSSKdBsChT5naSAC82SlEhRxu-Cf2PrRsuossae4y7gJMLtcAKJEj1C_R8EyRgks1HJVivnmrsM7p2T7lmIzOv45xI-1wd1KPqAI', isMain: true }],
    categories: [{ name: 'V60', slug: 'v60' }],
    version: 1,
    created_at: Date.now(),
  },
  {
    PK: 'PRODUCT#kettle',
    SK: 'METADATA',
    name: 'The Obsidian Kettle',
    description: 'Sleek matte obsidian black gooseneck electric kettle on a dark marble countertop with a single highlight on its curve',
    price: 185.00,
    stock: 5,
    media: [{ type: 'image', key: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDgCmftKjkpUgwOZMOtFJNnA2jpSwaZbtrBeDbtTvpH8sySwxP6kYfdNE8Ek-JFZbSE6h_3iOuwritu0Oc8gGo195rU4WLNHz6yBZ9wC-GB3kArZ8cjW2E53gBhrL3wNt4EOYl_r9ZMI7QV93nKIXAae-tYB9WPzcaMnVaGvwfeTrapfFm1n8IKqCIZESWejZ6rXKOgw31D0lnbFJosbLR58QSi50pSsNrzIFNyIaCWx5PmT3g_AwlPgnpWLqZ_3U9S4ByMunH-DpY', isMain: true }],
    categories: [{ name: 'Kettles', slug: 'kettles' }],
    version: 1,
    created_at: Date.now(),
  },
  {
    PK: 'PRODUCT#grinder',
    SK: 'METADATA',
    name: 'C40 Nitro Blade',
    description: 'Artisanal hand coffee grinder with wooden handle and brushed steel body standing on a neutral parchment background',
    price: 250.00,
    stock: 0,
    media: [{ type: 'image', key: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBupUbNf5iqMPuFD4C2hSZCjDsxJaR3Aj-rdho1K3hMVU9i6mYSi1tQ2aZhwtS2HMuRWadxiRZ5hfoJaGl4xD_ZaEi8Tc7oIfK_bafQva_d4uatGtFmN-pEJnNpvM3iJckrdGxDK2P8XebBQdp-bvMAKCu2j4d0CYgGFukzavDmD1N6tgzcEsd-se1mJqT-Ow06vnxkYGQhPKUQyDWSrNJy4YQhtW14Y4X2A0Txnpdl-zavjkEgM8NTUw3T8JqKR1HvPnySDFBH-Ro', isMain: true }],
    categories: [{ name: 'Grinders', slug: 'grinders' }],
    version: 1,
    created_at: Date.now(),
  },
  {
    PK: 'PRODUCT#moka',
    SK: 'METADATA',
    name: 'Bialetti Special Edition',
    description: 'Classic aluminum Moka Pot with a modern architectural twist, placed on a light beige concrete surface',
    price: 55.00,
    stock: 8,
    media: [{ type: 'image', key: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD3l5F1K0bFWAOwI10PerjbYwB6iwv5QOmLVg7BAfAXmLbrhc1IkgBaTClLwvNTrtIVxgtxc1fT64gNzLBD4RQey-eJfzdV8E49Jv5eF5gT7lSfw4liFNObgFQsE3tUxb3CRwWGEqEbEOGyNgZxVjayEpdWwnWYFy8Q-VjxoeB46LOjG4sIyTSj7BkMgbqOoTe4fTdtgxZQW--HMTtSEXE6P2agdzF35OPFhCvHrwf_QVjevDwkHChWpoQPfOXZ_2RMJRsYmJNt07E', isMain: true }],
    categories: [{ name: 'Moka Pots', slug: 'moka-pots' }],
    version: 1,
    created_at: Date.now(),
  },
  {
    PK: 'PRODUCT#aeropress',
    SK: 'METADATA',
    name: 'AeroPress Clear',
    description: 'AeroPress Go portable coffee maker set displayed neatly on a minimalist travel kit with soft focus background',
    price: 49.00,
    stock: 12,
    media: [{ type: 'image', key: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBnsfAx76F0EgtJqRE-IfuRh5Hl8ReyoI-7gTzTO79B3nAhAV_9A2r6znKp3IrE-qxgbbHph1PbUQag11c6AhpXiuaHQN6mWDSWfnzrbVCoIg6kgNWk9dnhAxg0Gcs3qBq23V07B-m6lgyW63Ps6HyU7bBFTN9FTr7VN1-bRB6obCR3KA8VJ4Ee2PX7ZuKFgomNFVeW17GvKdLsqOVu0kex3y2x_1G2_zR2fMLJG2v7Dc61UNDsLayEfIx2VevJHbbP14l8Ew-Z_28', isMain: true }],
    categories: [{ name: 'AeroPress', slug: 'aeropress' }],
    version: 1,
    created_at: Date.now(),
  },
];
